# -*- coding: utf-8 -*-
"""image_final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Y2HnuUyLrL9wknmZpy5GdxBiVm0ZuVJ
"""

import torchvision.datasets as datasets
import torchvision.transforms as transforms


transform = transforms.ToTensor()


train_dataset = datasets.EMNIST(root='./data', split='letters', train=True, download=True, transform=transform)


test_dataset = datasets.EMNIST(root='./data', split='letters', train=False, download=True, transform=transform)

print(f"Size of training dataset: {len(train_dataset)}")
print(f"Size of testing dataset: {len(test_dataset)}")

import matplotlib.pyplot as plt
import numpy as np

num_images = 20


random_indices = np.random.choice(len(train_dataset), num_images, replace=False)

label_map = {i + 1: chr(ord('a') + i) for i in range(26)}


plt.figure(figsize=(12, 8))


for i, index in enumerate(random_indices):
    image, label = train_dataset[index]

    plt.subplot(4, 5, i + 1)

    plt.imshow(image.squeeze(), cmap='gray')

    plt.title(f" {label_map[label]}")

    plt.axis('off')

plt.tight_layout()

plt.show()

import torch.nn as nn
import torch.nn.functional as F

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()

        self.conv1 = nn.Conv2d(1, 16, kernel_size=5, padding=2)

        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)


        self.conv2 = nn.Conv2d(16, 32, kernel_size=5, padding=2)

        self.fc1 = nn.Linear(32 * 7 * 7, 26)

    def forward(self, x):

        x = self.pool(F.relu(self.conv1(x)))

        x = self.pool(F.relu(self.conv2(x)))

        x = x.view(-1, 32 * 7 * 7)

        x = self.fc1(x)
        return x


model = SimpleCNN()

print(model)

import torch

def train_model(model, train_loader, optimizer, criterion, device):
    """
    Trains the CNN model for one epoch.

    Args:
        model: The CNN model to train.
        train_loader: The data loader for the training dataset.
        optimizer: The optimizer for updating model weights.
        criterion: The loss function (Cross-Entropy Loss).
        device: The device to train on ('cuda' or 'cpu').

    Returns:
        The average loss for the epoch.
    """
    model.train()
    running_loss = 0.0
    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)


        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()


    epoch_loss = running_loss / len(train_loader)
    return epoch_loss

import torch

def test_model(model, test_loader, device):
    """
    Tests the CNN model and calculates its accuracy.

    Args:
        model: The trained CNN model.
        test_loader: The data loader for the testing dataset.
        device: The device to test on ('cuda' or 'cpu').

    Returns:
        The accuracy of the model on the test dataset.
    """
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in test_loader:

            images = images.to(device)
            labels = labels.to(device)


            outputs = model(images)


            _, predicted = torch.max(outputs.data, 1)


            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    accuracy = 100 * correct / total
    return accuracy

import torch
import torch.optim as optim
import time
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import torch.nn as nn
import torch.nn.functional as F


transform = transforms.Compose([
    transforms.ToTensor(),

])


train_dataset = datasets.EMNIST(root='./data', split='letters', train=True, download=True, transform=transform, target_transform=lambda x: x - 1)

test_dataset = datasets.EMNIST(root='./data', split='letters', train=False, download=True, transform=transform, target_transform=lambda x: x - 1)

num_epochs = 10
batch_size = 128


train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 16, kernel_size=5, padding=2)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=5, padding=2)
        self.fc1 = nn.Linear(32 * 7 * 7, 26)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 32 * 7 * 7)
        x = self.fc1(x)
        return x

model = SimpleCNN()


criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr=0.001)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
print(f"Training on device: {device}")

def train_model(model, train_loader, optimizer, criterion, device):
    model.train()
    running_loss = 0.0
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    epoch_loss = running_loss / len(train_loader)
    return epoch_loss

def test_model(model, test_loader, device):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(device)
            labels = labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    accuracy = 100 * correct / total
    return accuracy



train_losses = []
start_time = time.time()

print("Starting training...")
for epoch in range(num_epochs):
    epoch_start_time = time.time()
    epoch_loss = train_model(model, train_loader, optimizer, criterion, device)
    train_losses.append(epoch_loss)
    epoch_end_time = time.time()
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss:.4f}, Time: {epoch_end_time - epoch_start_time:.2f}s")

end_time = time.time()
total_training_time = end_time - start_time
print(f"Finished Training in {total_training_time:.2f} seconds")

accuracy = test_model(model, test_loader, device)
print(f"Test Accuracy: {accuracy:.2f}%")

final_accuracy = accuracy
training_losses_history = train_losses

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(range(1, num_epochs + 1), training_losses_history)
plt.xlabel('Epoch')
plt.ylabel('Training Loss')
plt.title('Training Loss over Epochs')
plt.grid(True)
plt.show()

import torch
import os

def save_model(model, accuracy, epochs, batch_size, optimizer_name, lr):
    """
    Saves the trained PyTorch model to a .pth file with informative filename.

    Args:
        model: The trained PyTorch model.
        accuracy: The test accuracy achieved by the model.
        epochs: The number of training epochs.
        batch_size: The batch size used for training.
        optimizer_name: The name of the optimizer used.
        lr: The learning rate used.
    """

    if not os.path.exists('saved_models'):
        os.makedirs('saved_models')


    filename = f"saved_models/model_acc{accuracy:.2f}_epochs{epochs}_batch{batch_size}_{optimizer_name}_lr{lr}.pth"

    torch.save(model.state_dict(), filename)

    print(f"Model saved to: {filename}")

import torch.nn as nn
import torch.nn.functional as F
import torch
import torch.optim as optim
import time
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

transform = transforms.Compose([
    transforms.ToTensor(),

])


train_dataset = datasets.EMNIST(root='./data', split='letters', train=True, download=True, transform=transform, target_transform=lambda x: x - 1)


test_dataset = datasets.EMNIST(root='./data', split='letters', train=False, download=True, transform=transform, target_transform=lambda x: x - 1)


class ComplexCNN(nn.Module):
    def __init__(self):
        super(ComplexCNN, self).__init__()

        self.conv1 = nn.Conv2d(1, 32, kernel_size=5, padding=2)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)


        self.conv2 = nn.Conv2d(32, 64, kernel_size=5, padding=2)

        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)


        self.fc1 = nn.Linear(128 * 7 * 7, 512)
        self.fc2 = nn.Linear(512, 26)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = F.relu(self.conv3(x))
        x = x.view(-1, 128 * 7 * 7)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x


complex_model = ComplexCNN()


print("Complex CNN Architecture:")
print(complex_model)

criterion = nn.CrossEntropyLoss()


optimizer = optim.Adam(complex_model.parameters(), lr=0.001)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
complex_model.to(device)
print(f"\nTraining complex model on device: {device}")


num_epochs_complex = 15
batch_size_complex = 128

train_loader = DataLoader(train_dataset, batch_size=batch_size_complex, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size_complex, shuffle=False)

print("Starting training of Complex CNN...")
train_losses_complex = []
start_time_complex = time.time()

for epoch in range(num_epochs_complex):
    complex_model.train()
    running_loss = 0.0
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        outputs = complex_model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

    epoch_loss = running_loss / len(train_loader)
    train_losses_complex.append(epoch_loss)
    print(f"Complex CNN - Epoch [{epoch+1}/{num_epochs_complex}], Loss: {epoch_loss:.4f}")


end_time_complex = time.time()
total_training_time_complex = end_time_complex - start_time_complex
print(f"Finished Training Complex CNN in {total_training_time_complex:.2f} seconds")

accuracy_complex = test_model(complex_model, test_loader, device)
print(f"Complex CNN Test Accuracy: {accuracy_complex:.2f}%")

print("\nComplex CNN Training Results:")
print("Architecture:")
print(complex_model)
print(f"Number of Epochs: {num_epochs_complex}")
print(f"Batch Size: {batch_size_complex}")
print(f"Total Training Time: {total_training_time_complex:.2f} seconds")
print(f"Achieved Test Accuracy: {accuracy_complex:.2f}%")
print(f"Training performed on: {device}")

import torch.nn as nn
import torch.nn.functional as F
import torch
import torch.optim as optim
import time
from torch.utils.data import DataLoader
from torchvision import datasets, transforms


transform = transforms.Compose([
    transforms.ToTensor(),
])

train_dataset = datasets.EMNIST(root='./data', split='letters', train=True, download=True, transform=transform, target_transform=lambda x: x - 1)

test_dataset = datasets.EMNIST(root='./data', split='letters', train=False, download=True, transform=transform, target_transform=lambda x: x - 1)

batch_size = 128
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def train_model(model, train_loader, optimizer, criterion, device):
    model.train()
    running_loss = 0.0
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    epoch_loss = running_loss / len(train_loader)
    return epoch_loss

def test_model(model, test_loader, device):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(device)
            labels = labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    accuracy = 100 * correct / total
    return accuracy


class CNN_variation1(nn.Module):
    def __init__(self):
        super(CNN_variation1, self).__init__()

        self.conv1 = nn.Conv2d(1, 64, kernel_size=5, padding=2)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)


        self.conv2 = nn.Conv2d(64, 128, kernel_size=5, padding=2)
        self.fc1 = nn.Linear(128 * 7 * 7, 26)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 128 * 7 * 7)
        x = self.fc1(x)
        return x

# Define CNN Variation 2 (Changed Kernel Sizes)
class CNN_variation2(nn.Module):
    def __init__(self):
        super(CNN_variation2, self).__init__()
        self.conv1 = nn.Conv2d(1, 16, kernel_size=3, padding=1) # Changed from 5x5 to 3x3
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        self.conv2 = nn.Conv2d(16, 32, kernel_size=7, padding=3) # Changed from 5x5 to 7x7

        self.fc1 = nn.Linear(32 * 7 * 7, 26)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 32 * 7 * 7)
        x = self.fc1(x)
        return x

num_epochs = 15


print("Training CNN Variation 1 (Changed Output Channels)")
model_var1 = CNN_variation1().to(device)
optimizer_var1 = optim.Adam(model_var1.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

train_losses_var1 = []
start_time_var1 = time.time()

for epoch in range(num_epochs):
    epoch_loss = train_model(model_var1, train_loader, optimizer_var1, criterion, device)
    train_losses_var1.append(epoch_loss)
    print(f"Var1 - Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss:.4f}")

end_time_var1 = time.time()
total_training_time_var1 = end_time_var1 - start_time_var1
print(f"Finished Training CNN Variation 1 in {total_training_time_var1:.2f} seconds")

accuracy_var1 = test_model(model_var1, test_loader, device)
print(f"CNN Variation 1 Test Accuracy: {accuracy_var1:.2f}%")

print("\n--- Training CNN Variation 2 (Changed Kernel Sizes) ---")
model_var2 = CNN_variation2().to(device)
optimizer_var2 = optim.Adam(model_var2.parameters(), lr=0.001)


train_losses_var2 = []
start_time_var2 = time.time()

for epoch in range(num_epochs):
    epoch_loss = train_model(model_var2, train_loader, optimizer_var2, criterion, device)
    train_losses_var2.append(epoch_loss)
    print(f"Var2 - Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss:.4f}")

end_time_var2 = time.time()
total_training_time_var2 = end_time_var2 - start_time_var2
print(f"Finished Training CNN Variation 2 in {total_training_time_var2:.2f} seconds")

accuracy_var2 = test_model(model_var2, test_loader, device)
print(f"CNN Variation 2 Test Accuracy: {accuracy_var2:.2f}%")

print("\n--- overall Results was---")
print("CNN Variation 1 (Changed Output Channels):")
print("Architecture:")
print(model_var1)
print(f"Total Training Time: {total_training_time_var1:.2f} seconds")
print(f"Achieved Test Accuracy: {accuracy_var1:.2f}%")

print("\nCNN Variation 2 (Changed Kernel Sizes):")
print("Architecture:")
print(model_var2)
print(f"Total Training Time: {total_training_time_var2:.2f} seconds")
print(f"Achieved Test Accuracy: {accuracy_var2:.2f}%")

import torch
import torch.optim as optim
import time
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import torch.nn as nn
import torch.nn.functional as F


transform = transforms.Compose([
    transforms.ToTensor(),

])

train_dataset = datasets.EMNIST(root='./data', split='letters', train=True, download=True, transform=transform, target_transform=lambda x: x - 1)

test_dataset = datasets.EMNIST(root='./data', split='letters', train=False, download=True, transform=transform, target_transform=lambda x: x - 1)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Experimenting on device: {device}")

def train_model(model, train_loader, optimizer, criterion, device):
    model.train()
    running_loss = 0.0
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    epoch_loss = running_loss / len(train_loader)
    return epoch_loss

def test_model(model, test_loader, device):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(device)
            labels = labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    accuracy = 100 * correct / total
    return accuracy

class ComplexCNN(nn.Module):
    def __init__(self):
        super(ComplexCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=5, padding=2)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=5, padding=2)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(128 * 7 * 7, 512)
        self.fc2 = nn.Linear(512, 26)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = F.relu(self.conv3(x))
        x = x.view(-1, 128 * 7 * 7)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

param_combinations = [
    {'learning_rate': 0.001, 'num_epochs': 10, 'batch_size': 64},
    {'learning_rate': 0.0005, 'num_epochs': 15, 'batch_size': 128},
    {'learning_rate': 0.002, 'num_epochs': 8, 'batch_size': 256}
]

results = []

for i, params in enumerate(param_combinations):
    lr = params['learning_rate']
    epochs = params['num_epochs']
    bs = params['batch_size']

    print(f"\n--- Experiment {i+1}/{len(param_combinations)} ---")
    print(f"Parameters: Learning Rate={lr}, Epochs={epochs}, Batch Size={bs}")

    model = ComplexCNN().to(device)

    optimizer = optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    train_loader = DataLoader(train_dataset, batch_size=bs, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=bs, shuffle=False)

    print("Starting training...")
    train_losses = []
    start_time = time.time()

    for epoch in range(epochs):
        epoch_loss = train_model(model, train_loader, optimizer, criterion, device)
        train_losses.append(epoch_loss)
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {epoch_loss:.4f}")

    end_time = time.time()
    total_training_time = end_time - start_time
    print(f"Finished Training in {total_training_time:.2f} seconds")

    accuracy = test_model(model, test_loader, device)
    print(f"Test Accuracy: {accuracy:.2f}%")

    results.append({
        'parameters': params,
        'total_training_time': total_training_time,
        'test_accuracy': accuracy,
        'training_losses': train_losses # Optional: store losses for plotting later if needed
    })
print("\n--- Experiment Results Summary ---")
for i, result in enumerate(results):
    print(f"\nExperiment {i+1}:")
    print(f"  Parameters: {result['parameters']}")
    print(f"  Total Training Time: {result['total_training_time']:.2f} seconds")
    print(f"  Test Accuracy: {result['test_accuracy']:.2f}%")

import torch
import torch.optim as optim
import time
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import torch.nn as nn
import torch.nn.functional as F
import os

transform = transforms.Compose([
    transforms.ToTensor(),

])


train_dataset = datasets.EMNIST(root='./data', split='letters', train=True, download=True, transform=transform, target_transform=lambda x: x - 1)

test_dataset = datasets.EMNIST(root='./data', split='letters', train=False, download=True, transform=transform, target_transform=lambda x: x - 1)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Training best model on device: {device}")

def train_model(model, train_loader, optimizer, criterion, device):
    model.train()
    running_loss = 0.0
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    epoch_loss = running_loss / len(train_loader)
    return epoch_loss

def test_model(model, test_loader, device):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(device)
            labels = labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    accuracy = 100 * correct / total
    return accuracy

class ComplexCNN(nn.Module):
    def __init__(self):
        super(ComplexCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=5, padding=2)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=5, padding=2)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(128 * 7 * 7, 512)
        self.fc2 = nn.Linear(512, 26)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = F.relu(self.conv3(x))
        x = x.view(-1, 128 * 7 * 7)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x


def save_model(model, accuracy, epochs, batch_size, optimizer_name, lr):
    """
    Saves the trained PyTorch model to a .pth file with informative filename.

    Args:
        model: The trained PyTorch model.
        accuracy: The test accuracy achieved by the model.
        epochs: The number of training epochs.
        batch_size: The batch size used for training.
        optimizer_name: The name of the optimizer used.
        lr: The learning rate used.
    """
    if not os.path.exists('saved_models'):
        os.makedirs('saved_models')

    filename = f"saved_models/best_letter_model_acc{accuracy:.2f}_epochs{epochs}_batch{batch_size}_{optimizer_name}_lr{lr}.pth"

    torch.save(model.state_dict(), filename)

    print(f"Model saved to: {filename}")

best_params = {'learning_rate': 0.002, 'num_epochs': 8, 'batch_size': 256}
best_lr = best_params['learning_rate']
best_epochs = best_params['num_epochs']
best_bs = best_params['batch_size']

print(f"Training best model with parameters: Learning Rate={best_lr}, Epochs={best_epochs}, Batch Size={best_bs}")


best_model = ComplexCNN().to(device)

best_optimizer = optim.Adam(best_model.parameters(), lr=best_lr)
criterion = nn.CrossEntropyLoss()

best_train_loader = DataLoader(train_dataset, batch_size=best_bs, shuffle=True)
best_test_loader = DataLoader(test_dataset, batch_size=best_bs, shuffle=False)

print("Starting training of the best model...")
start_time = time.time()
train_losses = []

for epoch in range(best_epochs):
    epoch_loss = train_model(best_model, best_train_loader, best_optimizer, criterion, device)
    train_losses.append(epoch_loss)
    print(f"Epoch [{epoch+1}/{best_epochs}], Loss: {epoch_loss:.4f}")

end_time = time.time()
total_training_time = end_time - start_time
print(f"Finished Training the best model in {total_training_time:.2f} seconds")

final_accuracy = test_model(best_model, best_test_loader, device)
print(f"Best Model Test Accuracy: {final_accuracy:.2f}%")

save_model(best_model, final_accuracy, best_epochs, best_bs, 'Adam', best_lr)

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.ToTensor(),

])

train_dataset_digits = datasets.EMNIST(root='./data', split='digits', train=True, download=True, transform=transform)

test_dataset_digits = datasets.EMNIST(root='./data', split='digits', train=False, download=True, transform=transform)

print(f"Size of digits training dataset: {len(train_dataset_digits)}")
print(f"Size of digits testing dataset: {len(test_dataset_digits)}")

import torch
import torch.nn as nn
import torch.nn.functional as F


model_path = "saved_models/best_letter_model_acc93.36_epochs8_batch256_Adam_lr0.002.pth"

class ComplexCNN(nn.Module):
    def __init__(self):
        super(ComplexCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=5, padding=2)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=5, padding=2)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(128 * 7 * 7, 512)
        self.fc2 = nn.Linear(512, 26)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = F.relu(self.conv3(x))
        x = x.view(-1, 128 * 7 * 7)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x


best_letter_model = ComplexCNN()


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
best_letter_model.to(device)

try:
    best_letter_model.load_state_dict(torch.load(model_path, map_location=device))
    print(f"Successfully loaded model state dictionary from {model_path}")
except FileNotFoundError:
    print(f"Error: Model file not found at {model_path}")
except Exception as e:
    print(f"An error occurred while loading the model: {e}")

best_letter_model.eval()

print(f"Model loaded onto device: {device}")

import torch.nn as nn

in_features_fc2 = best_letter_model.fc2.in_features


best_letter_model.fc2 = nn.Linear(in_features_fc2, 10)

print("Modified model architecture with final layer changed for digit classification:")
print(best_letter_model)

print(f"\nOutput features of the modified fc2 layer: {best_letter_model.fc2.out_features}")

for name, param in best_letter_model.named_parameters():

    if 'fc2' not in name:

        param.requires_grad = False


print("Verifying requires_grad status:")
for name, param in best_letter_model.named_parameters():

    if 'conv' in name or 'fc1' in name or 'fc2' in name:
         print(f"Parameter: {name}, requires_grad: {param.requires_grad}")

print("\nAll parameters except those in 'fc2' should have requires_grad=False.")

import torch

def train_transfer_learning_model(model, train_loader, optimizer, criterion, device):
    model.train()
    running_loss = 0.0
    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels)


        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    epoch_loss = running_loss / len(train_loader)
    return epoch_loss

import torch
import torch.optim as optim
import time
from torch.utils.data import DataLoader
import torch.nn as nn

from torchvision import datasets, transforms

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Starting transfer learning training on device: {device}")

best_letter_model.to(device)


criterion = nn.CrossEntropyLoss()


optimizer = optim.Adam(filter(lambda p: p.requires_grad, best_letter_model.parameters()), lr=0.001)

num_epochs_transfer = 5
batch_size_transfer = 256

print(f"Training parameters: Epochs={num_epochs_transfer}, Batch Size={batch_size_transfer}")

train_loader_digits = DataLoader(train_dataset_digits, batch_size=batch_size_transfer, shuffle=True)
test_loader_digits = DataLoader(test_dataset_digits, batch_size=batch_size_transfer, shuffle=False)

print("Starting transfer learning training:")
start_time_transfer = time.time()
train_losses_transfer = []

for epoch in range(num_epochs_transfer):

    epoch_loss = train_transfer_learning_model(best_letter_model, train_loader_digits, optimizer, criterion, device)
    train_losses_transfer.append(epoch_loss)
    print(f"Transfer Learning - Epoch [{epoch+1}/{num_epochs_transfer}], Loss: {epoch_loss:.4f}")

end_time_transfer = time.time()
total_training_time_transfer = end_time_transfer - start_time_transfer
print(f"Finished Transfer Learning Training in {total_training_time_transfer:.2f} seconds")

final_transfer_learning_time = total_training_time_transfer
transfer_learning_train_losses = train_losses_transfer

def save_model(model, accuracy, epochs, batch_size, optimizer_name, lr):


    if not os.path.exists('saved_models'):
        os.makedirs('saved_models')

    filename = f"saved_models/model_digit_acc{accuracy:.2f}_epochs{epochs}_batch{batch_size}_{optimizer_name}_lr{lr}.pth"

    torch.save(model.state_dict(), filename)

    print(f"Model saved to: {filename}")

transfer_learning_accuracy = test_model(best_letter_model, test_loader_digits, device)

print(f"\nTransfer Learning Model Test Accuracy: {transfer_learning_accuracy:.2f}%")


final_transfer_learning_accuracy = transfer_learning_accuracy

save_model(best_letter_model, final_transfer_learning_accuracy, num_epochs_transfer, batch_size_transfer, 'Adam', 0.001)

import torch
from PIL import Image
import torchvision.transforms as transforms
import torch.nn.functional as F

def predict_image(model, image_input, transform, device):

    model.eval()

    if isinstance(image_input, str):
        try:

            image = Image.open(image_input)


            if image.mode != 'L':
                image = image.convert('L')


            image = transform(image)


            image = image.unsqueeze(0)
        except FileNotFoundError:
            print(f"Error: Image file not found at {image_input}")
            return None, None
        except Exception as e:
            print(f"An error occurred while loading or processing the image: {e}")
            return None, None

    elif isinstance(image_input, torch.Tensor):

        image = image_input

    else:
        print("Error: image_input must be a file path (str) or a PyTorch Tensor.")
        return None, None

    image = image.to(device)

    with torch.no_grad():
        outputs = model(image)


    probabilities = torch.softmax(outputs, dim=1)

    predicted_class_index = torch.argmax(probabilities, dim=1)


    return predicted_class_index.item(), probabilities[0]

import os

print("EMNIST 'letters' test dataset loaded:", 'test_dataset' in globals())
print("EMNIST 'digits' test dataset loaded:", 'test_dataset_digits' in globals())

import torch
import torch.nn as nn
import torch.nn.functional as F
import os

model_path = "saved_models/best_letter_model_acc93.36_epochs8_batch256_Adam_lr0.002.pth"

class ComplexCNN(nn.Module):
    def __init__(self):
        super(ComplexCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=5, padding=2)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=5, padding=2)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(128 * 7 * 7, 512)
        self.fc2 = nn.Linear(512, 26)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = F.relu(self.conv3(x))
        x = x.view(-1, 128 * 7 * 7)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

best_letter_model_task_b = ComplexCNN()


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
best_letter_model_task_b.to(device)


try:
    best_letter_model_task_b.load_state_dict(torch.load(model_path, map_location=device))
    print(f"Successfully loaded model state dictionary from {model_path}")
except FileNotFoundError:
    print(f"Error: Model file not found at {model_path}")
except Exception as e:
    print(f"An error occurred while loading the model: {e}")

best_letter_model_task_b.eval()

print(f"Model loaded onto device: {device}")

import torch
import torch.nn as nn
import torch.nn.functional as F
import os

class ComplexCNN(nn.Module):
    def __init__(self):
        super(ComplexCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=5, padding=2)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=5, padding=2)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(128 * 7 * 7, 512)
        self.fc2 = nn.Linear(512, 26)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = F.relu(self.conv3(x))
        x = x.view(-1, 128 * 7 * 7)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x


transfer_learning_digit_model = ComplexCNN()

in_features_fc2 = transfer_learning_digit_model.fc2.in_features
transfer_learning_digit_model.fc2 = nn.Linear(in_features_fc2, 10)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
transfer_learning_digit_model.to(device)


model_path = "saved_models/model_digit_acc99.20_epochs5_batch256_Adam_lr0.001.pth"

try:

    transfer_learning_digit_model.load_state_dict(torch.load(model_path, map_location=device), strict=False)
    print(f"Successfully loaded state dictionary from {model_path} into the modified model.")
    print("Note: This loads the state of the best letter model up to fc1. The fc2 layer was randomly initialized when modified.")

except FileNotFoundError:
    print(f"Error: Model file not found at {model_path}")
except Exception as e:
    print(f"An error occurred while loading the model: {e}")


transfer_learning_digit_model.eval()

print(f"Transfer learning digit classification model loaded onto device: {device}")

from torchvision import datasets, transforms


transform = transforms.Compose([
    transforms.ToTensor(),

])

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device for letter inference: {device}")

best_letter_model_task_b.to(device)
best_letter_model_task_b.eval()


label_map_letters = {i + 1: chr(ord('a') + i) for i in range(26)}

print("\nClassifying a subset of EMNIST 'letters' test images:")
num_samples_to_show = 10

for i in range(num_samples_to_show):

    image, true_label_original = test_dataset[i]
    true_label_mapped = label_map_letters[true_label_original + 1]


    image = image.unsqueeze(0)

    predicted_index, probabilities = predict_image(best_letter_model_task_b, image, transform, device)

    predicted_label_mapped = label_map_letters[predicted_index + 1]


    print(f"Sample {i+1}: True Label: {true_label_mapped}, Predicted Label: {predicted_label_mapped}")

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.ToTensor(),

])

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device for digit inference: {device}")

transfer_learning_digit_model.to(device)
transfer_learning_digit_model.eval()

label_map_digits = {i: str(i) for i in range(10)}


print("\nClassifying a subset of EMNIST 'digits' test images:")
num_samples_to_show = 10

for i in range(num_samples_to_show):

    image_digit, true_label_digit = test_dataset_digits[i]


    true_label_digit_mapped = label_map_digits[true_label_digit]


    image_digit = image_digit.unsqueeze(0)

    predicted_index_digit, probabilities_digit = predict_image(transfer_learning_digit_model, image_digit, transform, device)


    predicted_label_digit_mapped = label_map_digits[predicted_index_digit]


    print(f"Sample {i+1}: True Label: {true_label_digit_mapped}, Predicted Label: {predicted_label_digit_mapped}")

import os
from PIL import Image
import torchvision.transforms as transforms


self_generated_images_dir = './self_generated_images/letters'


transform = transforms.Compose([

    transforms.ToTensor()
])


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

try:
    best_letter_model_task_b.to(device)
    best_letter_model_task_b.eval()
    transfer_learning_digit_model.to(device)
    transfer_learning_digit_model.eval()
    print(f"Models ready on device: {device}")
except NameError:
    print("Error: Trained models (best_letter_model_task_b and/or transfer_learning_digit_model) are not available in the environment. Please run previous cells to load/train them.")

    exit()


label_map_letters = {i + 1: chr(ord('a') + i) for i in range(26)}
label_map_digits = {i: str(i) for i in range(10)}

print(f"\nClassifying self-generated images from {self_generated_images_dir}:")


if os.path.exists(self_generated_images_dir):
    for filename in os.listdir(self_generated_images_dir):
        filepath = os.path.join(self_generated_images_dir, filename)

        if os.path.isfile(filepath) and filename.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.gif')):
            print(f"\nClassifying image: {filename}")

            try:

                image = Image.open(filepath)

                image = image.convert('L')


                image_tensor = transform(image)


                image_tensor = image_tensor.unsqueeze(0)

                predicted_index_letter, probabilities_letter = predict_image(best_letter_model_task_b, image_tensor, None, device) # Pass None for transform as it's already applied

                if predicted_index_letter is not None:

                    predicted_label_letter = label_map_letters.get(predicted_index_letter + 1, "Unknown")
                    print(f"  Letter Classifier Prediction: {predicted_label_letter}")





            except FileNotFoundError:
                 print(f"  Error: Image file not found at {filepath}")
            except Exception as e:
                 print(f"  An error occurred while processing image {filename}: {e}")
else:
    print(f"Error: Directory not found at {self_generated_images_dir}")

self_generated_images_dir = './self_generated_images/digits'
if os.path.exists(self_generated_images_dir):
    for filename in os.listdir(self_generated_images_dir):
        filepath = os.path.join(self_generated_images_dir, filename)


        if os.path.isfile(filepath) and filename.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.gif')):
            print(f"\nClassifying image: {filename}")

            try:

                image = Image.open(filepath)


                image = image.convert('L')


                image_tensor = transform(image)


                image_tensor = image_tensor.unsqueeze(0)


                predicted_index_digit, probabilities_digit = predict_image(transfer_learning_digit_model, image_tensor, None, device) # Pass None for transform as it's already applied

                if predicted_index_digit is not None:

                    predicted_label_digit = label_map_digits.get(predicted_index_digit, "Unknown")
                    print(f"  Digit Classifier Prediction: {predicted_label_digit}")





            except FileNotFoundError:
                 print(f"  Error: Image file not found at {filepath}")
            except Exception as e:
                 print(f"  An error occurred while processing image {filename}: {e}")
else:
    print(f"Error: Directory not found at {self_generated_images_dir}")

import torchvision.transforms as transforms
from torch.utils.data import DataLoader

augmented_transform = transforms.Compose([
    transforms.RandomAffine(degrees=10, translate=(0.1, 0.1), scale=(0.9, 1.1)),
    transforms.ToTensor(),

])

train_dataset_digits_augmented = datasets.EMNIST(root='./data', split='digits', train=True, download=True, transform=augmented_transform)

test_transform = transforms.Compose([
    transforms.ToTensor(),
])
test_dataset_digits = datasets.EMNIST(root='./data', split='digits', train=False, download=True, transform=test_transform)


train_loader_digits_augmented = DataLoader(train_dataset_digits_augmented, batch_size=batch_size_transfer, shuffle=True)
test_loader_digits_augmented = DataLoader(test_dataset_digits, batch_size=batch_size_transfer, shuffle=False) # Use original test set

print("Data augmentation applied to the EMNIST 'digits' training dataset.")
print(f"Size of augmented training dataset: {len(train_dataset_digits_augmented)}")
print(f"Size of original testing dataset: {len(test_dataset_digits)}")